const plant = [{
    "pid": "red mini rose",
    "name": "rose",
    "display_pid": "Red mini rose",
    "alias": "red mini rose",
    "max_light_mmol": 8700,
    "min_light_mmol": 4200,
    "max_light_lux": 60000,
    "min_light_lux": 3000,
    "max_temp": 35,
    "min_temp": 8,
    "max_env_humid": 80,
    "min_env_humid": 30,
    "max_soil_moist": 75,
    "min_soil_moist": 16,
    "max_soil_ec": 2000,
    "min_soil_ec": 425,
    "image_url": "https://objectstorage.ap-sydney-1.oraclecloud.com/n/sdyd5yr3jypo/b/plant-img/o/red%20mini%20rose.jpg"
},
{
    "pid": "ipomoea purpurea",
    "name": "morning glory",
    "display_pid": "Ipomoea purpurea",
    "alias": "ipomoea purpurea",
    "max_light_mmol": 6000,
    "min_light_mmol": 3600,
    "max_light_lux": 60000,
    "min_light_lux": 3000,
    "max_temp": 35,
    "min_temp": 5,
    "max_env_humid": 80,
    "min_env_humid": 30,
    "max_soil_moist": 60,
    "min_soil_moist": 15,
    "max_soil_ec": 2000,
    "min_soil_ec": 350,
    "image_url": "https://objectstorage.ap-sydney-1.oraclecloud.com/n/sdyd5yr3jypo/b/plant-img/o/ipomoea%20purpurea.jpg"
},
{
    "pid": "aloe vera",
    "name": "aloe vera",
    "display_pid": "Aloe vera",
    "alias": "aloe vera",
    "max_light_mmol": 6400,
    "min_light_mmol": 3200,
    "max_light_lux": 70000,
    "min_light_lux": 3000,
    "max_temp": 35,
    "min_temp": 8,
    "max_env_humid": 80,
    "min_env_humid": 15,
    "max_soil_moist": 50,
    "min_soil_moist": 7,
    "max_soil_ec": 1000,
    "min_soil_ec": 300,
    "image_url": "https://objectstorage.ap-sydney-1.oraclecloud.com/n/sdyd5yr3jypo/b/plant-img/o/aloe%20vera.jpg"
},
{
    "pid": "hibiscus rosa sinensis 'cheerleader clear yellow'",
    "name": "hibiscus",
    "display_pid": "Hibiscus rosa sinensis 'Cheerleader Clear Yellow'",
    "alias": "hawaiian hibiscus",
    "max_light_mmol": 7100,
    "min_light_mmol": 3400,
    "max_light_lux": 55000,
    "min_light_lux": 2500,
    "max_temp": 35,
    "min_temp": 5,
    "max_env_humid": 80,
    "min_env_humid": 30,
    "max_soil_moist": 60,
    "min_soil_moist": 15,
    "max_soil_ec": 2000,
    "min_soil_ec": 350,
    "image_url": "https://objectstorage.ap-sydney-1.oraclecloud.com/n/sdyd5yr3jypo/b/plant-img/o/hibiscus%20rosa%20sinensis%20%27cheerleader%20clear%20yellow%27.jpg"
},
{
    "pid": "epipremnum aureum 'golden pothos'",
    "name": "money plant",
    "display_pid": "Epipremnum aureum 'Golden Pothos'",
    "alias": "epipremnum aureum",
    "max_light_mmol": 3200,
    "min_light_mmol": 700,
    "max_light_lux": 12000,
    "min_light_lux": 500,
    "max_temp": 32,
    "min_temp": 10,
    "max_env_humid": 85,
    "min_env_humid": 30,
    "max_soil_moist": 60,
    "min_soil_moist": 15,
    "max_soil_ec": 2000,
    "min_soil_ec": 350,
    "image_url": "https://objectstorage.ap-sydney-1.oraclecloud.com/n/sdyd5yr3jypo/b/plant-img/o/epipremnum%20aureum%20%27golden%20pothos%27.jpg"
},
{
    "pid": "daphne jasminea",
    "name": "jasmine",
    "display_pid": "Daphne jasminea",
    "alias": "daphne jasminea",
    "max_light_mmol": 3000,
    "min_light_mmol": 1500,
    "max_light_lux": 15000,
    "min_light_lux": 800,
    "max_temp": 32,
    "min_temp": 8,
    "max_env_humid": 80,
    "min_env_humid": 30,
    "max_soil_moist": 60,
    "min_soil_moist": 15,
    "max_soil_ec": 2000,
    "min_soil_ec": 350,
    "image_url": "https://objectstorage.ap-sydney-1.oraclecloud.com/n/sdyd5yr3jypo/b/plant-img/o/daphne%20jasminea.jpg"
},
{
    "pid": "champagne mini rose",
    "name": "rose",
    "display_pid": "Champagne mini rose",
    "alias": "champagne mini rose",
    "max_light_mmol": 8700,
    "min_light_mmol": 4200,
    "max_light_lux": 60000,
    "min_light_lux": 3000,
    "max_temp": 35,
    "min_temp": 8,
    "max_env_humid": 80,
    "min_env_humid": 30,
    "max_soil_moist": 75,
    "min_soil_moist": 16,
    "max_soil_ec": 2000,
    "min_soil_ec": 425,
    "image_url": "https://objectstorage.ap-sydney-1.oraclecloud.com/n/sdyd5yr3jypo/b/plant-img/o/champagne%20mini%20rose.jpg"
},
{
    "pid": "tagetes lucida",
    "name": "marigold",
    "display_pid": "Tagetes lucida",
    "alias": "tagetes lucida",
    "max_light_mmol": 6400,
    "min_light_mmol": 3200,
    "max_light_lux": 55000,
    "min_light_lux": 3000,
    "max_temp": 32,
    "min_temp": 8,
    "max_env_humid": 80,
    "min_env_humid": 15,
    "max_soil_moist": 60,
    "min_soil_moist": 20,
    "max_soil_ec": 2000,
    "min_soil_ec": 350,
    "image_url": "https://objectstorage.ap-sydney-1.oraclecloud.com/n/sdyd5yr3jypo/b/plant-img/o/tagetes%20lucida.jpg"
},
{
    "pid": "tagetes ground control",
    "name": "marigold",
    "display_pid": "Tagetes Ground Control",
    "alias": "tagetes ground control",
    "max_light_mmol": 6400,
    "min_light_mmol": 3200,
    "max_light_lux": 55000,
    "min_light_lux": 3000,
    "max_temp": 32,
    "min_temp": 8,
    "max_env_humid": 80,
    "min_env_humid": 15,
    "max_soil_moist": 60,
    "min_soil_moist": 20,
    "max_soil_ec": 2000,
    "min_soil_ec": 350,
    "image_url": "https://objectstorage.ap-sydney-1.oraclecloud.com/n/sdyd5yr3jypo/b/plant-img/o/tagetes%20ground%20control.jpg"
},

]

module.exports = plant